#define KEYWORDS 1
#define IDENTIFIERS 2
#define INTEGER 3
#define FLOAT    4
#define ENUM     5
#define CCHAR   6
#define SCHAR   7
#define PUNCTUATORS 8
#define SCMNT   9
#define MLCMNT   10
#define OTHERS 11