#define ADD_OPP       1
#define SUB_OPP       2
#define MUL_OPP       3
#define DIV_OPP       4
#define MOD_OPP       5
#define UNI_AND       6
#define UNI_OR        7
#define INCREMENT     8
#define DECREMENT     9
#define EQUALS       10
#define TILDE        11
#define NOT          12
#define SEMI_COL     13